package com.bob.android.clgl.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bob.android.clgl.entity.DriverEntity;

import com.bob.android.clgl.database.greendao.DriverEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig driverEntityDaoConfig;

    private final DriverEntityDao driverEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        driverEntityDaoConfig = daoConfigMap.get(DriverEntityDao.class).clone();
        driverEntityDaoConfig.initIdentityScope(type);

        driverEntityDao = new DriverEntityDao(driverEntityDaoConfig, this);

        registerDao(DriverEntity.class, driverEntityDao);
    }
    
    public void clear() {
        driverEntityDaoConfig.clearIdentityScope();
    }

    public DriverEntityDao getDriverEntityDao() {
        return driverEntityDao;
    }

}
