package com.bob.android.clgl.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bob.android.clgl.entity.DriverEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DRIVER_ENTITY".
*/
public class DriverEntityDao extends AbstractDao<DriverEntity, Long> {

    public static final String TABLENAME = "DRIVER_ENTITY";

    /**
     * Properties of entity DriverEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DriverNum = new Property(1, String.class, "driverNum", false, "DRIVER_NUM");
        public final static Property DriverName = new Property(2, String.class, "driverName", false, "DRIVER_NAME");
    }


    public DriverEntityDao(DaoConfig config) {
        super(config);
    }
    
    public DriverEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DRIVER_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DRIVER_NUM\" TEXT," + // 1: driverNum
                "\"DRIVER_NAME\" TEXT);"); // 2: driverName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DRIVER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DriverEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String driverNum = entity.getDriverNum();
        if (driverNum != null) {
            stmt.bindString(2, driverNum);
        }
 
        String driverName = entity.getDriverName();
        if (driverName != null) {
            stmt.bindString(3, driverName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DriverEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String driverNum = entity.getDriverNum();
        if (driverNum != null) {
            stmt.bindString(2, driverNum);
        }
 
        String driverName = entity.getDriverName();
        if (driverName != null) {
            stmt.bindString(3, driverName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DriverEntity readEntity(Cursor cursor, int offset) {
        DriverEntity entity = new DriverEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // driverNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // driverName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DriverEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDriverNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDriverName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DriverEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DriverEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DriverEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
